In [1]:
# import os
import pandas as pd
# import cv2
# import matplotlib.pyplot as plt
# import numpy as np
# import math
# import tensorflow as tf
import pycaret

# %matplotlib inline

In [2]:
print('PyCaret: %s' % pycaret.__version__)

PyCaret: 3.1.0

In [3]:
train=pd.read_csv('training.csv')
test=pd.read_csv('testing.csv')
data=pd.read_csv('total_data.csv')

In [4]:
test.head()

,number,gender,age,mean_r,mean_g,mean_b,mean_rg,HHR,Ent,B,G1,G2,G3,G4,G5,label,hgb
0,4,1.0,39.0,168.003551,142.526411,171.719288,41.573798,0.007344,1248.653137,153.478341,3.447792,3.346256,6.161600e-02,2.564352,49.143024,1,8.3
1,5,1.0,29.0,161.395007,128.240333,153.480755,58.491050,0.031040,873.921511,141.151901,3.134768,2.984544,7.098667e-02,2.302943,41.525760,1,7.8
2,8,0.0,32.0,171.092908,112.428535,139.891132,77.786821,0.104768,1146.306784,132.693683,3.844800,3.963088,4.575467e-02,2.932350,42.328048,0,13.0
3,9,0.0,32.0,159.498131,90.163154,131.569181,69.875430,0.032320,654.198938,115.642262,2.347872,2.530512,3.765333e-02,1.780206,17.336144,0,11.5
4,24,1.0,23.0,148.109619,114.570254,139.216847,65.133211,0.052416,1220.238916,127.424177,3.555808,3.648384,2.090000e-17,2.645822,41.912336,0,13.4

In [5]:
data.shape

(95, 18)

In [6]:
data.drop('gender_actual',axis=1,inplace=True)
data.head()

,number,gender,age,mean_r,mean_g,mean_b,mean_rg,HHR,Ent,B,G1,G2,G3,G4,G5,label,hgb
0,1,0,29,162.253551,110.344051,140.106420,66.783275,0.051072,1125.472761,129.062154,3.390000,3.542816,-6.590000e-18,2.562056,40.268672,0,12.2
1,2,1,36,93.155839,57.903152,82.817630,46.735631,0.024032,564.048278,68.833649,1.175424,1.272608,1.460000e-17,0.917702,8.827232,1,8.0
2,3,1,30,156.337977,127.740262,153.386077,54.392947,0.017872,695.100841,139.239840,2.593296,2.793504,-8.640000e-18,2.032372,28.944064,1,10.7
3,4,1,39,168.003551,142.526411,171.719288,41.573798,0.007344,1248.653137,153.478341,3.447792,3.346256,6.161600e-02,2.564352,49.143024,1,8.3
4,5,1,29,161.395007,128.240333,153.480755,58.491050,0.031040,873.921511,141.151901,3.134768,2.984544,7.098667e-02,2.302943,41.525760,1,7.8

# Classification

In [7]:
from pycaret.classification import *
s = setup(data, target='label', ignore_features=['hgb','number','mean_b','mean_rg','B','G2','G4','G5'], preprocess=False, session_id=123)

In [8]:
best = compare_models()

In [9]:
print(best)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [11]:
predict_model(best)

,gender,age,mean_r,mean_g,HHR,Ent,G1,G3,label,prediction_label,prediction_score
82,0,21,139.383469,110.304169,0.004176,1156.383545,3.398464,-6.000000e-17,0,1,0.6296
40,0,50,158.528137,115.850685,0.023936,1556.830078,3.143632,5.767467e-02,0,0,0.6838
44,1,27,153.427780,125.572662,0.009152,973.510803,3.237856,4.359467e-02,1,1,0.8801
29,0,21,156.974426,112.577255,0.055600,1290.696777,3.118512,5.252800e-02,0,0,0.8154
84,0,63,174.089142,114.623878,0.083632,856.029663,2.989552,3.759467e-02,0,0,0.9920
36,0,22,166.368286,112.309319,0.054544,1061.522217,3.131440,-6.590000e-18,0,0,0.9745
56,1,33,165.212814,134.037689,0.020160,1549.722778,4.083440,1.167840e-01,1,1,0.7620
70,0,20,149.536163,97.357994,0.077664,1122.102905,2.918544,3.517867e-02,0,0,0.9508
55,1,55,160.529892,123.020470,0.020832,967.807495,2.685088,1.460000e-17,1,1,0.7440
7,0,32,171.092911,112.428535,0.104768,1146.306763,3.844800,4.575467e-02,0,0,0.9957
64,0,32,168.538757,117.839493,0.080672,1230.512573,3.257472,1.410000e-17,0,0,0.9489
61,0,27,170.198181,123.456688,0.058528,1286.911133,3.369248,5.548800e-02,0,0,0.9039
32,0,21,161.650681,130.893677,0.053456,1347.709229,4.433232,7.283733e-02,0,0,0.7129
41,1,19,156.106735,112.115211,0.061840,744.415283,2.041424,3.578133e-02,1,1,0.6283
25,1,39,153.158020,119.083847,0.025696,869.275452,2.549312,8.190000e-18,1,1,0.8478
78,0,29,173.068008,103.557938,0.176032,1093.750610,2.566560,-1.180000e-17,0,0,0.9960
65,0,21,146.545151,108.970924,0.043024,886.594788,3.286768,3.254400e-02,0,0,0.7857
35,1,20,161.850357,112.057854,0.064928,1225.655273,3.514768,9.373867e-02,1,0,0.8766
47,0,39,153.093216,109.798309,0.034576,1143.709106,3.876768,-3.180000e-18,0,0,0.9434
2,1,30,156.337982,127.740265,0.017872,695.100830,2.593296,-8.640000e-18,1,1,0.9154
54,0,65,165.097244,118.224052,0.057808,1264.162842,4.232304,8.804267e-02,1,0,0.9777
12,1,71,168.029465,122.503365,0.047488,1424.154907,3.287136,2.960000e-17,1,0,0.6260
20,0,21,171.034882,120.378502,0.055344,977.105896,3.924000,-5.460000e-18,0,0,0.9877
52,0,32,154.407227,104.368683,0.047056,1129.359985,4.309616,9.090000e-19,0,0,0.9914
39,1,29,146.412842,110.379616,0.016368,1048.772217,2.913168,-3.180000e-17,1,1,0.7464
87,0,23,140.636963,85.511909,0.049104,974.031006,3.040240,2.934400e-02,0,0,0.9826
88,0,23,150.005249,104.451767,0.045520,734.097412,3.145584,2.852800e-02,0,0,0.9430
13,1,29,147.171402,118.196144,0.072272,1173.893433,3.655584,5.177600e-02,1,1,0.8090
21,0,21,147.792404,108.325592,0.003504,734.471680,2.388976,2.180000e-17,1,0,0.6222

In [12]:
# predict_model(best,data=test.drop(['hgb','number'],axis=1))

In [13]:
# predict_model(best,data=train.drop(['hgb','number'],axis=1))

# Regression

In [14]:
from pycaret.regression import *
s = setup(data, target='hgb', ignore_features=['label','number','mean_b','mean_rg','B','G2','G4','G5'], preprocess=False, session_id=123)

In [15]:
best = compare_models()

In [16]:
print(best)

<catboost.core.CatBoostRegressor object at 0x000001ADAF2143A0>

In [17]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [18]:
predict_model(best)

,gender,age,mean_r,mean_g,HHR,Ent,G1,G3,hgb,prediction_label
71,0,39,180.564011,133.586380,0.042976,1515.020508,3.861520,1.182507e-01,12.7,11.752650
62,1,27,147.257614,110.858734,0.057680,1068.863770,3.348688,4.755733e-02,9.9,9.912755
29,0,21,156.974426,112.577255,0.055600,1290.696777,3.118512,5.252800e-02,11.2,11.382636
53,0,45,165.063965,120.138626,0.046496,1127.878906,3.703312,1.406400e-02,15.5,12.515708
90,0,21,162.090378,108.563744,0.058944,853.474426,2.795376,9.780000e-18,13.4,13.190789
4,1,29,161.395004,128.240326,0.031040,873.921509,3.134768,7.098667e-02,7.8,10.111141
31,0,21,146.312119,109.149147,0.065456,1051.250854,3.139952,4.553067e-02,11.3,13.168882
77,1,40,162.955994,137.199753,0.007760,1077.874146,3.238320,5.453333e-02,10.3,9.482735
79,1,50,157.484863,120.734703,0.036960,866.780334,2.965072,9.090000e-19,10.5,9.648380
70,0,20,149.536163,97.357994,0.077664,1122.102905,2.918544,3.517867e-02,15.0,14.525822
33,1,20,148.730042,106.107452,0.073072,1010.755249,2.911216,3.221333e-02,11.4,11.267652
51,0,42,151.390976,99.205429,0.086064,1166.888916,3.773616,3.180000e-18,13.4,13.992273
8,0,32,159.498138,90.163155,0.032320,654.198914,2.347872,3.765333e-02,11.5,12.915709
63,1,62,195.729843,163.511322,0.024064,1851.026123,3.535824,-3.180000e-17,9.2,11.704112
85,1,30,152.064774,117.575638,0.027648,1009.374817,3.179136,3.539200e-02,8.5,9.576702
35,1,20,161.850357,112.057854,0.064928,1225.655273,3.514768,9.373867e-02,9.7,10.169372
28,0,21,151.668213,110.786057,0.064288,1028.322632,3.103696,5.954667e-02,12.4,12.165546
75,1,30,161.815979,127.637756,0.009360,882.675049,2.851264,3.684800e-02,9.3,9.995452
50,0,34,163.210648,110.751732,0.058144,733.689453,3.377168,-6.370000e-18,12.9,12.921411
41,1,19,156.106735,112.115211,0.061840,744.415283,2.041424,3.578133e-02,8.1,11.636362
65,0,21,146.545151,108.970924,0.043024,886.594788,3.286768,3.254400e-02,13.8,13.207614
23,1,23,148.109619,114.570251,0.052416,1220.238892,3.555808,2.090000e-17,13.4,9.587611
64,0,32,168.538757,117.839493,0.080672,1230.512573,3.257472,1.410000e-17,13.8,12.618679
56,1,33,165.212814,134.037689,0.020160,1549.722778,4.083440,1.167840e-01,10.3,9.945187
89,0,23,145.546173,107.117317,0.020288,1021.397461,3.598624,3.609067e-02,11.9,13.706016
24,1,30,143.501862,109.373093,0.044928,754.440491,2.525936,5.000000e-18,9.2,9.693734
82,0,21,139.383469,110.304169,0.004176,1156.383545,3.398464,-6.000000e-17,13.7,12.016119
9,1,35,158.245331,86.470055,0.052320,537.676392,1.830768,1.129600e-02,11.3,10.775487
21,0,21,147.792404,108.325592,0.003504,734.471680,2.388976,2.180000e-17,10.7,12.503782

In [19]:
# predict_model(best,data=test.drop(['label','number'],axis=1))

In [20]:
# predict_model(best,data=train.drop(['label','number'],axis=1))